/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Settings = {
  _id: string;
  _type: "settings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Header = {
  _id: string;
  _type: "header";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  lefttext?: string;
  name?: string;
  workTitle?: string;
  projectCloseText?: string;
  navigationItems?: Array<{
    name?: string;
    slug?: Slug;
    _type: "navigationItem";
    _key: string;
  }>;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Footer = {
  _id: string;
  _type: "footer";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  lefttext?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  name?: string;
  rights?: string;
  timezone?: "Africa/Abidjan" | "Africa/Accra" | "Africa/Addis_Ababa" | "Australia/Adelaide" | "Africa/Algiers" | "Europe/Amsterdam" | "America/Anchorage" | "Europe/Athens" | "Pacific/Auckland" | "Asia/Bangkok" | "Europe/Berlin" | "America/Bogota" | "Australia/Brisbane" | "Europe/Brussels" | "Europe/Bucharest" | "America/Argentina/Buenos_Aires" | "Africa/Cairo" | "America/Cancun" | "America/Caracas" | "Africa/Casablanca" | "America/Chicago" | "Europe/Copenhagen" | "America/Denver" | "Asia/Dhaka" | "Asia/Dubai" | "Europe/Dublin" | "America/Guatemala" | "America/Havana" | "Europe/Helsinki" | "Asia/Hong_Kong" | "Pacific/Honolulu" | "Europe/Istanbul" | "Asia/Jakarta" | "Asia/Jerusalem" | "Africa/Johannesburg" | "Asia/Karachi" | "Asia/Kathmandu" | "America/Jamaica" | "Asia/Kuala_Lumpur" | "Asia/Kuwait" | "Europe/Kiev" | "Africa/Lagos" | "America/Lima" | "Europe/Lisbon" | "Europe/London" | "America/Los_Angeles" | "Europe/Madrid" | "Asia/Manila" | "Australia/Melbourne" | "America/Mexico_City" | "Europe/Moscow" | "Asia/Kolkata" | "Africa/Nairobi" | "America/New_York" | "America/Panama" | "Europe/Paris" | "Australia/Perth" | "America/Phoenix" | "Europe/Prague" | "Asia/Riyadh" | "Europe/Rome" | "America/Santiago" | "America/Sao_Paulo" | "Asia/Seoul" | "Asia/Shanghai" | "Asia/Singapore" | "Europe/Stockholm" | "Pacific/Fiji" | "Australia/Sydney" | "Asia/Taipei" | "Asia/Tehran" | "Asia/Tokyo" | "America/Toronto" | "Africa/Tunis" | "America/Vancouver" | "Europe/Vienna" | "Europe/Warsaw" | "America/Whitehorse" | "Europe/Zurich";
  location?: string;
};

export type MediaType = {
  _type: "mediaType";
  mediaType?: "image" | "video";
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  video?: MuxVideo;
};

export type MediaGallery = {
  _type: "mediaGallery";
  mediaItems?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
};

export type Studies = {
  _id: string;
  _type: "studies";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  degree?: string;
  institution?: string;
  startDate?: string;
  endDate?: string;
};

export type SoftwareTools = {
  _id: string;
  _type: "softwareTools";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  category?: string;
  richText?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type Skills = {
  _id: string;
  _type: "skills";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
};

export type Publications = {
  _id: string;
  _type: "publications";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  href?: string;
};

export type Projects = {
  _id: string;
  _type: "projects";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  comingSoon?: boolean;
  slug?: Slug;
  richText?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  year?: string;
  mediaBackgroundColor?: Color;
  mediaGallery?: MediaGallery;
  layout?: "firstLayout" | "secondLayout" | "thirdLayout";
  sectionList?: Array<{
    _key: string;
  } & Section | {
    _key: string;
  } & RelatedProjects>;
  seo?: {
    title?: string;
    description?: string;
    image?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
  };
};

export type Color = {
  _type: "color";
  hex?: string;
  alpha?: number;
  hsl?: HslaColor;
  hsv?: HsvaColor;
  rgb?: RgbaColor;
};

export type Languages = {
  _id: string;
  _type: "languages";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: string;
  level?: string;
};

export type Experiences = {
  _id: string;
  _type: "experiences";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  location?: string;
  role?: string;
  startDate?: string;
  endDate?: string;
};

export type Section = {
  _type: "section";
  richText?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  richTextBottom?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  mediaGallery?: MediaGallery;
  sectionBgColor?: string;
};

export type RelatedProjects = {
  _type: "relatedProjects";
  projects?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "projects";
  }>;
};

export type BlockContent = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h1" | "h2" | "h3" | "h4" | "blockquote";
  listItem?: "bullet";
  markDefs?: Array<{
    href?: string;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
} | {
  asset?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
  };
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
  _type: "image";
  _key: string;
}>;

export type ProjectsIndex = {
  _id: string;
  _type: "projectsIndex";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  projects?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "projects";
  }>;
  seo?: {
    title?: string;
    description?: string;
    image?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
  };
};

export type HomePage = {
  _id: string;
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  enterSiteLogo?: MediaType;
  enterSiteText?: string;
  projects?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "projects";
  }>;
  seo?: {
    title?: string;
    description?: string;
    image?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
  };
};

export type MuxVideo = {
  _type: "mux.video";
  asset?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "mux.videoAsset";
  };
};

export type ContactPage = {
  _id: string;
  _type: "contactPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  richText?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h2";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  seo?: {
    title?: string;
    description?: string;
    image?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
  };
};

export type AboutPage = {
  _id: string;
  _type: "aboutPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  languages?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "languages";
  }>;
  experiences?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "experiences";
  }>;
  studies?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "studies";
  }>;
  publications?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "publications";
  }>;
  portrait?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  bodyTextSections?: Array<{
    title?: string;
    content?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h2";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    _type: "richTextSection";
    _key: string;
  }>;
  skills?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "skills";
  }>;
  softwareTools?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "softwareTools";
  }>;
  seo?: {
    title?: string;
    description?: string;
    image?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
  };
};

export type RgbaColor = {
  _type: "rgbaColor";
  r?: number;
  g?: number;
  b?: number;
  a?: number;
};

export type HsvaColor = {
  _type: "hsvaColor";
  h?: number;
  s?: number;
  v?: number;
  a?: number;
};

export type HslaColor = {
  _type: "hslaColor";
  h?: number;
  s?: number;
  l?: number;
  a?: number;
};

export type MuxVideoAsset = {
  _id: string;
  _type: "mux.videoAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  status?: string;
  assetId?: string;
  playbackId?: string;
  filename?: string;
  thumbTime?: number;
  data?: MuxAssetData;
};

export type MuxAssetData = {
  _type: "mux.assetData";
  resolution_tier?: string;
  upload_id?: string;
  created_at?: string;
  id?: string;
  status?: string;
  max_stored_resolution?: string;
  passthrough?: string;
  encoding_tier?: string;
  master_access?: string;
  aspect_ratio?: string;
  duration?: number;
  max_stored_frame_rate?: number;
  mp4_support?: string;
  max_resolution_tier?: string;
  tracks?: Array<{
    _key: string;
  } & MuxTrack>;
  playback_ids?: Array<{
    _key: string;
  } & MuxPlaybackId>;
  static_renditions?: MuxStaticRenditions;
};

export type MuxStaticRenditions = {
  _type: "mux.staticRenditions";
  status?: string;
  files?: Array<{
    _key: string;
  } & MuxStaticRenditionFile>;
};

export type MuxStaticRenditionFile = {
  _type: "mux.staticRenditionFile";
  ext?: string;
  name?: string;
  width?: number;
  bitrate?: number;
  filesize?: number;
  height?: number;
};

export type MuxPlaybackId = {
  _type: "mux.playbackId";
  id?: string;
  policy?: string;
};

export type MuxTrack = {
  _type: "mux.track";
  id?: string;
  type?: string;
  max_width?: number;
  max_frame_rate?: number;
  duration?: number;
  max_height?: number;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes = Settings | SanityImageCrop | SanityImageHotspot | Header | Slug | Footer | MediaType | MediaGallery | Studies | SoftwareTools | Skills | Publications | Projects | Color | Languages | Experiences | Section | RelatedProjects | BlockContent | ProjectsIndex | HomePage | MuxVideo | ContactPage | AboutPage | RgbaColor | HsvaColor | HslaColor | MuxVideoAsset | MuxAssetData | MuxStaticRenditions | MuxStaticRenditionFile | MuxPlaybackId | MuxTrack | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageMetadata | SanityFileAsset | SanityAssetSourceData | SanityImageAsset | Geopoint;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./src/sanity/lib/queries.ts
// Variable: fetchSeo
// Query: *[_type == "homePage" && (_id == "homePage" || _id == "drafts.homePage")][0]{  seo {  title,  description,  image {    _type,    asset  }}}
export type FetchSeoResult = {
  seo: {
    title: string | null;
    description: string | null;
    image: {
      _type: "image";
      asset: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      } | null;
    } | null;
  } | null;
} | null;
// Variable: fetchSeoTitle
// Query: *[_type == "projects" && slug.current == $slug][0]{    title,    seo {      title,      description,      image {        _type,        asset      }    }  }
export type FetchSeoTitleResult = {
  title: string | null;
  seo: {
    title: string | null;
    description: string | null;
    image: {
      _type: "image";
      asset: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      } | null;
    } | null;
  } | null;
} | null;
// Variable: settingsQuery
// Query: *[_type == "settings" && (_id == "settings" || _id == "drafts.settings")][0]{  _id,  title,  description,  title,  description,  image {    _type,    asset  }}
export type SettingsQueryResult = {
  _id: string;
  title: string | null;
  description: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  image: {
    _type: "image";
    asset: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    } | null;
  } | null;
} | null;
// Variable: fetchHeaderQuery
// Query: *[_type == "header" && (_id == "header" || _id == "drafts.header")][0]{    _id,    _type,    lefttext,    name,    workTitle,    projectCloseText,    // Menu order is the array order, which editors drag to rearrange. It drives    // the rendered menu, the breadcrumb labels and the site structure sent to    // search engines.    navigationItems[]{      _key,      name,      "slug": slug.current    }  }
export type FetchHeaderQueryResult = {
  _id: string;
  _type: "header";
  lefttext: string | null;
  name: string | null;
  workTitle: string | null;
  projectCloseText: string | null;
  navigationItems: Array<{
    _key: string;
    name: string | null;
    slug: string | null;
  }> | null;
} | null;
// Variable: fetchHomePageQuery
// Query: *[_type == "homePage" && (_id == "homePage" || _id == "drafts.homePage")][0]{    _id,    _type,    enterSiteText,    enterSiteLogo {      mediaType,      image {        alt,        asset-> {          _id,          url,          metadata        }      },      video {        asset-> {          _id,          playbackId,          assetId,          filename,          url        }      }    },    projects[]->{    _id,    name,    "slug": slug.current,    title,    year,    richText,    mediaBackgroundColor,    mediaGallery {      _type,      mediaItems[] {        _key,        _id,        alt,        asset-> {          _id,          _ref,          playbackId,          assetId,          filename,          url        }      }    },    comingSoon    },    seo {    title,    description,    image {      _type,      asset    }  }  }
export type FetchHomePageQueryResult = {
  _id: string;
  _type: "homePage";
  enterSiteText: string | null;
  enterSiteLogo: {
    mediaType: "image" | "video" | null;
    image: {
      alt: string | null;
      asset: {
        _id: string;
        url: string | null;
        metadata: SanityImageMetadata | null;
      } | null;
    } | null;
    video: {
      asset: {
        _id: string;
        playbackId: string | null;
        assetId: string | null;
        filename: string | null;
        url: null;
      } | null;
    } | null;
  } | null;
  projects: Array<{
    _id: string;
    name: null;
    slug: string | null;
    title: string | null;
    year: string | null;
    richText: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }> | null;
    mediaBackgroundColor: Color | null;
    mediaGallery: {
      _type: "mediaGallery";
      mediaItems: Array<{
        _key: string;
        _id: null;
        alt: string | null;
        asset: {
          _id: string;
          _ref: null;
          playbackId: null;
          assetId: string | null;
          filename: null;
          url: string | null;
        } | null;
      }> | null;
    } | null;
    comingSoon: boolean | null;
  }> | null;
  seo: {
    title: string | null;
    description: string | null;
    image: {
      _type: "image";
      asset: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      } | null;
    } | null;
  } | null;
} | null;
// Variable: fetchProjectsIndexQuery
// Query: *[_type == "projectsIndex" && (_id == "projectsIndex" || _id == "drafts.projectsIndex")][0]{    _id,    _type,    projects[]->{    _id,    name,    "slug": slug.current,    title,    year,    richText,    mediaBackgroundColor,    mediaGallery {      _type,      mediaItems[] {        _key,        _id,        alt,        asset-> {          _id,          _ref,          playbackId,          assetId,          filename,          url        }      }    },    comingSoon,    seo {      title,      description,      image {        _type,        asset      }    }    },    seo {      title,      description,      image {        _type,        asset      }    }  }
export type FetchProjectsIndexQueryResult = {
  _id: string;
  _type: "projectsIndex";
  projects: Array<{
    _id: string;
    name: null;
    slug: string | null;
    title: string | null;
    year: string | null;
    richText: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }> | null;
    mediaBackgroundColor: Color | null;
    mediaGallery: {
      _type: "mediaGallery";
      mediaItems: Array<{
        _key: string;
        _id: null;
        alt: string | null;
        asset: {
          _id: string;
          _ref: null;
          playbackId: null;
          assetId: string | null;
          filename: null;
          url: string | null;
        } | null;
      }> | null;
    } | null;
    comingSoon: boolean | null;
    seo: {
      title: string | null;
      description: string | null;
      image: {
        _type: "image";
        asset: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        } | null;
      } | null;
    } | null;
  }> | null;
  seo: {
    title: string | null;
    description: string | null;
    image: {
      _type: "image";
      asset: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      } | null;
    } | null;
  } | null;
} | null;
// Variable: singleProjectQuery
// Query: *[_type == "projects" && slug.current == $slug][0]{    _id,    _type,    title,    comingSoon,    "slug": slug.current,    year,    richText,    mediaBackgroundColor,    mediaGallery {      _type,      mediaItems[] {        _key,        alt,        asset-> {          _id,          _ref,          playbackId,          assetId,          filename,          url        }      }    },    layout,    sectionList[] {      _type,      _key,      richText,      richTextBottom,      sectionBgColor,      mediaGallery {      _type,      mediaItems[] {        _key,        alt,        asset-> {          _id,          _ref,          playbackId,          assetId,          filename,          url        }        }      },      projects[]->{        _id,        title,        "slug": slug.current,        comingSoon,        year,        mediaBackgroundColor,        mediaGallery {      _type,      mediaItems[] {        _key,        alt,        asset-> {            _id,            _ref,            playbackId,            assetId,            filename,            url          }        }      },      }    },    seo {      title,      description,      image {        _type,        asset      }    }  }
export type SingleProjectQueryResult = {
  _id: string;
  _type: "projects";
  title: string | null;
  comingSoon: boolean | null;
  slug: string | null;
  year: string | null;
  richText: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  mediaBackgroundColor: Color | null;
  mediaGallery: {
    _type: "mediaGallery";
    mediaItems: Array<{
      _key: string;
      alt: string | null;
      asset: {
        _id: string;
        _ref: null;
        playbackId: null;
        assetId: string | null;
        filename: null;
        url: string | null;
      } | null;
    }> | null;
  } | null;
  layout: "firstLayout" | "secondLayout" | "thirdLayout" | null;
  sectionList: Array<{
    _type: "relatedProjects";
    _key: string;
    richText: null;
    richTextBottom: null;
    sectionBgColor: null;
    mediaGallery: null;
    projects: Array<{
      _id: string;
      title: string | null;
      slug: string | null;
      comingSoon: boolean | null;
      year: string | null;
      mediaBackgroundColor: Color | null;
      mediaGallery: {
        _type: "mediaGallery";
        mediaItems: Array<{
          _key: string;
          alt: string | null;
          asset: {
            _id: string;
            _ref: null;
            playbackId: null;
            assetId: string | null;
            filename: null;
            url: string | null;
          } | null;
        }> | null;
      } | null;
    }> | null;
  } | {
    _type: "section";
    _key: string;
    richText: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }> | null;
    richTextBottom: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }> | null;
    sectionBgColor: string | null;
    mediaGallery: {
      _type: "mediaGallery";
      mediaItems: Array<{
        _key: string;
        alt: string | null;
        asset: {
          _id: string;
          _ref: null;
          playbackId: null;
          assetId: string | null;
          filename: null;
          url: string | null;
        } | null;
      }> | null;
    } | null;
    projects: null;
  }> | null;
  seo: {
    title: string | null;
    description: string | null;
    image: {
      _type: "image";
      asset: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      } | null;
    } | null;
  } | null;
} | null;
// Variable: fetchAboutQuery
// Query: *[_type == "aboutPage" && (_id == "aboutPage" || _id == "drafts.aboutPage")][0]{    _id,    _type,    languages[]->{      _id,      _type,      language,      level    },    experiences[]->{      _id,      _type,      title,      location,      role,      startDate,      endDate    },    studies[]->{      _id,      _type,      degree,      institution,      startDate,      endDate    },    publications[]->{      _id,      _type,      title,      href    },    portrait {      _type,      asset    },    bodyTextSections[]{      _key,      title,      content    },    skills[]->{      _id,      _type,      title    },    softwareTools[]->{      _id,      _type,      richText    },    seo {      title,      description,      image {        _type,        asset      }    }  }
export type FetchAboutQueryResult = {
  _id: string;
  _type: "aboutPage";
  languages: Array<{
    _id: string;
    _type: "languages";
    language: string | null;
    level: string | null;
  }> | null;
  experiences: Array<{
    _id: string;
    _type: "experiences";
    title: string | null;
    location: string | null;
    role: string | null;
    startDate: string | null;
    endDate: string | null;
  }> | null;
  studies: Array<{
    _id: string;
    _type: "studies";
    degree: string | null;
    institution: string | null;
    startDate: string | null;
    endDate: string | null;
  }> | null;
  publications: Array<{
    _id: string;
    _type: "publications";
    title: string | null;
    href: string | null;
  }> | null;
  portrait: {
    _type: "image";
    asset: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    } | null;
  } | null;
  bodyTextSections: Array<{
    _key: string;
    title: string | null;
    content: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "h2" | "normal";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }> | null;
  }> | null;
  skills: Array<{
    _id: string;
    _type: "skills";
    title: string | null;
  }> | null;
  softwareTools: Array<{
    _id: string;
    _type: "softwareTools";
    richText: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }> | null;
  }> | null;
  seo: {
    title: string | null;
    description: string | null;
    image: {
      _type: "image";
      asset: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      } | null;
    } | null;
  } | null;
} | null;
// Variable: fetchContactQuery
// Query: *[_type == "contactPage" && (_id == "contactPage" || _id == "drafts.contactPage")][0]{  _id,  _type,  richText,  seo {    title,    description,    image {      _type,      asset    }  }}
export type FetchContactQueryResult = {
  _id: string;
  _type: "contactPage";
  richText: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "h2" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  seo: {
    title: string | null;
    description: string | null;
    image: {
      _type: "image";
      asset: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      } | null;
    } | null;
  } | null;
} | null;
// Variable: fetchFooterQuery
// Query: *[_type == "footer" && (_id == "footer" || _id == "drafts.footer")][0]{    _id,    _type,    name,    rights,    timezone,    location,    lefttext  }
export type FetchFooterQueryResult = {
  _id: string;
  _type: "footer";
  name: string | null;
  rights: string | null;
  timezone: "Africa/Abidjan" | "Africa/Accra" | "Africa/Addis_Ababa" | "Africa/Algiers" | "Africa/Cairo" | "Africa/Casablanca" | "Africa/Johannesburg" | "Africa/Lagos" | "Africa/Nairobi" | "Africa/Tunis" | "America/Anchorage" | "America/Argentina/Buenos_Aires" | "America/Bogota" | "America/Cancun" | "America/Caracas" | "America/Chicago" | "America/Denver" | "America/Guatemala" | "America/Havana" | "America/Jamaica" | "America/Lima" | "America/Los_Angeles" | "America/Mexico_City" | "America/New_York" | "America/Panama" | "America/Phoenix" | "America/Santiago" | "America/Sao_Paulo" | "America/Toronto" | "America/Vancouver" | "America/Whitehorse" | "Asia/Bangkok" | "Asia/Dhaka" | "Asia/Dubai" | "Asia/Hong_Kong" | "Asia/Jakarta" | "Asia/Jerusalem" | "Asia/Karachi" | "Asia/Kathmandu" | "Asia/Kolkata" | "Asia/Kuala_Lumpur" | "Asia/Kuwait" | "Asia/Manila" | "Asia/Riyadh" | "Asia/Seoul" | "Asia/Shanghai" | "Asia/Singapore" | "Asia/Taipei" | "Asia/Tehran" | "Asia/Tokyo" | "Australia/Adelaide" | "Australia/Brisbane" | "Australia/Melbourne" | "Australia/Perth" | "Australia/Sydney" | "Europe/Amsterdam" | "Europe/Athens" | "Europe/Berlin" | "Europe/Brussels" | "Europe/Bucharest" | "Europe/Copenhagen" | "Europe/Dublin" | "Europe/Helsinki" | "Europe/Istanbul" | "Europe/Kiev" | "Europe/Lisbon" | "Europe/London" | "Europe/Madrid" | "Europe/Moscow" | "Europe/Paris" | "Europe/Prague" | "Europe/Rome" | "Europe/Stockholm" | "Europe/Vienna" | "Europe/Warsaw" | "Europe/Zurich" | "Pacific/Auckland" | "Pacific/Fiji" | "Pacific/Honolulu" | null;
  location: string | null;
  lefttext: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
} | null;
// Variable: projectsQuery
// Query: *[_type == "projects" && defined(slug.current)][0...100]{    _id,    name,    "slug": slug.current,    title,    year,    richText,    mediaBackgroundColor,    mediaGallery {      _type,      mediaItems[] {        _key,        alt,        asset-> {          _id,          _ref,          playbackId,          assetId,          filename,          url        }      }    },    comingSoon,    seo {      title,      description,      image {        _type,        asset      }    }  }
export type ProjectsQueryResult = Array<{
  _id: string;
  name: null;
  slug: string | null;
  title: string | null;
  year: string | null;
  richText: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  mediaBackgroundColor: Color | null;
  mediaGallery: {
    _type: "mediaGallery";
    mediaItems: Array<{
      _key: string;
      alt: string | null;
      asset: {
        _id: string;
        _ref: null;
        playbackId: null;
        assetId: string | null;
        filename: null;
        url: string | null;
      } | null;
    }> | null;
  } | null;
  comingSoon: boolean | null;
  seo: {
    title: string | null;
    description: string | null;
    image: {
      _type: "image";
      asset: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      } | null;
    } | null;
  } | null;
}>;
// Variable: sitemapQuery
// Query: {  "pages": *[_id in ["homePage", "projectsIndex", "aboutPage", "contactPage"]]{    _id,    _updatedAt  },  "projects": *[_type == "projects" && defined(slug.current)]{    "slug": slug.current,    _updatedAt  },  "nav": *[_type == "header" && _id == "header"][0].navigationItems[]{    "slug": slug.current  }}
export type SitemapQueryResult = {
  pages: Array<{
    _id: string;
    _updatedAt: string;
  }>;
  projects: Array<{
    slug: string | null;
    _updatedAt: string;
  }>;
  nav: Array<{
    slug: string | null;
  }> | null;
};

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "\n*[_type == \"homePage\" && (_id == \"homePage\" || _id == \"drafts.homePage\")][0]{\n  seo {\n  title,\n  description,\n  image {\n    _type,\n    asset\n  }\n}\n}\n": FetchSeoResult;
    "\n  *[_type == \"projects\" && slug.current == $slug][0]{\n    title,\n    seo {\n      title,\n      description,\n      image {\n        _type,\n        asset\n      }\n    }\n  }\n": FetchSeoTitleResult;
    "\n*[_type == \"settings\" && (_id == \"settings\" || _id == \"drafts.settings\")][0]{\n  _id,\n  title,\n  description,\n  title,\n  description,\n  image {\n    _type,\n    asset\n  }\n}\n": SettingsQueryResult;
    "\n  *[_type == \"header\" && (_id == \"header\" || _id == \"drafts.header\")][0]{\n    _id,\n    _type,\n    lefttext,\n    name,\n    workTitle,\n    projectCloseText,\n    // Menu order is the array order, which editors drag to rearrange. It drives\n    // the rendered menu, the breadcrumb labels and the site structure sent to\n    // search engines.\n    navigationItems[]{\n      _key,\n      name,\n      \"slug\": slug.current\n    }\n  }\n": FetchHeaderQueryResult;
    "\n  *[_type == \"homePage\" && (_id == \"homePage\" || _id == \"drafts.homePage\")][0]{\n    _id,\n    _type,\n    enterSiteText,\n    enterSiteLogo {\n      mediaType,\n      image {\n        alt,\n        asset-> {\n          _id,\n          url,\n          metadata\n        }\n      },\n      video {\n        asset-> {\n          _id,\n          playbackId,\n          assetId,\n          filename,\n          url\n        }\n      }\n    },\n    projects[]->{\n    _id,\n    name,\n    \"slug\": slug.current,\n    title,\n    year,\n    richText,\n    mediaBackgroundColor,\n    mediaGallery {\n      _type,\n      mediaItems[] {\n        _key,\n        _id,\n        alt,\n        asset-> {\n          _id,\n          _ref,\n          playbackId,\n          assetId,\n          filename,\n          url\n        }\n      }\n    },\n    comingSoon\n    },\n    seo {\n    title,\n    description,\n    image {\n      _type,\n      asset\n    }\n  }\n  }\n": FetchHomePageQueryResult;
    "\n  *[_type == \"projectsIndex\" && (_id == \"projectsIndex\" || _id == \"drafts.projectsIndex\")][0]{\n    _id,\n    _type,\n    projects[]->{\n    _id,\n    name,\n    \"slug\": slug.current,\n    title,\n    year,\n    richText,\n    mediaBackgroundColor,\n    mediaGallery {\n      _type,\n      mediaItems[] {\n        _key,\n        _id,\n        alt,\n        asset-> {\n          _id,\n          _ref,\n          playbackId,\n          assetId,\n          filename,\n          url\n        }\n      }\n    },\n    comingSoon,\n    seo {\n      title,\n      description,\n      image {\n        _type,\n        asset\n      }\n    }\n    },\n    seo {\n      title,\n      description,\n      image {\n        _type,\n        asset\n      }\n    }\n  }\n": FetchProjectsIndexQueryResult;
    "\n  *[_type == \"projects\" && slug.current == $slug][0]{\n    _id,\n    _type,\n    title,\n    comingSoon,\n    \"slug\": slug.current,\n    year,\n    richText,\n    mediaBackgroundColor,\n    mediaGallery {\n      _type,\n      mediaItems[] {\n        _key,\n        alt,\n        asset-> {\n          _id,\n          _ref,\n          playbackId,\n          assetId,\n          filename,\n          url\n        }\n      }\n    },\n    layout,\n    sectionList[] {\n      _type,\n      _key,\n      richText,\n      richTextBottom,\n      sectionBgColor,\n      mediaGallery {\n      _type,\n      mediaItems[] {\n        _key,\n        alt,\n        asset-> {\n          _id,\n          _ref,\n          playbackId,\n          assetId,\n          filename,\n          url\n        }\n        }\n      },\n      projects[]->{\n        _id,\n        title,\n        \"slug\": slug.current,\n        comingSoon,\n        year,\n        mediaBackgroundColor,\n        mediaGallery {\n      _type,\n      mediaItems[] {\n        _key,\n        alt,\n        asset-> {\n            _id,\n            _ref,\n            playbackId,\n            assetId,\n            filename,\n            url\n          }\n        }\n      },\n      }\n    },\n    seo {\n      title,\n      description,\n      image {\n        _type,\n        asset\n      }\n    }\n  }\n": SingleProjectQueryResult;
    "\n  *[_type == \"aboutPage\" && (_id == \"aboutPage\" || _id == \"drafts.aboutPage\")][0]{\n    _id,\n    _type,\n    languages[]->{\n      _id,\n      _type,\n      language,\n      level\n    },\n    experiences[]->{\n      _id,\n      _type,\n      title,\n      location,\n      role,\n      startDate,\n      endDate\n    },\n    studies[]->{\n      _id,\n      _type,\n      degree,\n      institution,\n      startDate,\n      endDate\n    },\n    publications[]->{\n      _id,\n      _type,\n      title,\n      href\n    },\n    portrait {\n      _type,\n      asset\n    },\n    bodyTextSections[]{\n      _key,\n      title,\n      content\n    },\n    skills[]->{\n      _id,\n      _type,\n      title\n    },\n    softwareTools[]->{\n      _id,\n      _type,\n      richText\n    },\n    seo {\n      title,\n      description,\n      image {\n        _type,\n        asset\n      }\n    }\n  }\n": FetchAboutQueryResult;
    "\n  *[_type == \"contactPage\" && (_id == \"contactPage\" || _id == \"drafts.contactPage\")][0]{\n  _id,\n  _type,\n  richText,\n  seo {\n    title,\n    description,\n    image {\n      _type,\n      asset\n    }\n  }\n}\n": FetchContactQueryResult;
    "\n  *[_type == \"footer\" && (_id == \"footer\" || _id == \"drafts.footer\")][0]{\n    _id,\n    _type,\n    name,\n    rights,\n    timezone,\n    location,\n    lefttext\n  }\n": FetchFooterQueryResult;
    "\n  *[_type == \"projects\" && defined(slug.current)][0...100]{\n    _id,\n    name,\n    \"slug\": slug.current,\n    title,\n    year,\n    richText,\n    mediaBackgroundColor,\n    mediaGallery {\n      _type,\n      mediaItems[] {\n        _key,\n        alt,\n        asset-> {\n          _id,\n          _ref,\n          playbackId,\n          assetId,\n          filename,\n          url\n        }\n      }\n    },\n    comingSoon,\n    seo {\n      title,\n      description,\n      image {\n        _type,\n        asset\n      }\n    }\n  }\n": ProjectsQueryResult;
    "{\n  \"pages\": *[_id in [\"homePage\", \"projectsIndex\", \"aboutPage\", \"contactPage\"]]{\n    _id,\n    _updatedAt\n  },\n  \"projects\": *[_type == \"projects\" && defined(slug.current)]{\n    \"slug\": slug.current,\n    _updatedAt\n  },\n  \"nav\": *[_type == \"header\" && _id == \"header\"][0].navigationItems[]{\n    \"slug\": slug.current\n  }\n}": SitemapQueryResult;
  }
}
